### ISSUE TITLE
no of repos retrieved

### ISSUE THREAD

**Issue by aadityaguptaa** [mshuber1981/github-react-portfolio-template#10]
The number of repositories the `https://api.github.com/users/${githubUsername}/repos` API returns is 30 maximum. Based on the logic used in the repo, if there are more than 30 repositories, it's possible that the repo-name provided in the filteredData array does not match with anything, and as a result the project might not get displayed.

I think I've found a solution though

tell me if I can create a PR to contribute, and I'll try to fix this

**Comment by mshuber1981** [comment]
Interesting, I should have taken the time to read the docs!

[https://docs.github.com/en/rest/repos/repos#list-repositories-for-a-user](https://docs.github.com/en/rest/repos/repos#list-repositories-for-a-user)

Are you thinking about something like this `https://api.github.com/users/${githubUsername}/repos?per_page=100`? Thank you for taking the time to point this out. I would be honored if you want to submit a pull request.


Have a nice weekend,

Mike

**Comment by mshuber1981** [comment]
@aadityaguptaa , I am going to implement the `per_page=100` solution above today and close this issue. If this does not solve your problem please create a new issue and associated pull request with your proposed changes.

Have a good week,

Mike
