### ISSUE TITLE
Images don't load when resizing and also not working for phone

### ISSUE THREAD

**Issue by mdabir1203** [mshuber1981/github-react-portfolio-template#37]
When I try to resize it to smaller than this .. This happens . Is there any solution for such? 

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/66947064/215612294-e476c9c2-16a2-4d3c-9cc7-c976464ded2d.png">

**Comment by mshuber1981** [comment]
This is where I am handling the hero image breakpoints - [https://github.com/mshuber1981/github-react-portfolio-template/blob/main/src/components/Hero.jsx#L62](https://github.com/mshuber1981/github-react-portfolio-template/blob/main/src/components/Hero.jsx#L62)

If you share a link to your project on GitHub I can find some time to take a look at any changes you made and see if I can help.

**Comment by mshuber1981** [comment]
I hope the info I shared was helpful, I am going to close this issue.
